language: android
android:
  components:
    # "tools" appears twice on purpose, leave it still
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-26

  licenses:
    - 'android-sdk-license-2742d1c5'

  install:
    - ./gradlew build -x test

  before_script:
    - echo SKIPPED

  script:
    - ./gradlew lint